name: Publish to Pub.dev

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish_flutter_web_optimizer:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout code'
        uses: actions/checkout@main # required!

      - name: '>> publish flutter_web_optimizer package to pub.dev <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.PUB_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUB_REFRESH_TOKEN }}
          skipTests: true
          format: true

#  publish_flutter_web_cos_upload_plugin:
#    runs-on: ubuntu-latest
#    steps:
#      - name: 'checkout code'
#        uses: actions/checkout@main # required!
#
#      - name: '>> publish flutter_web_cos_upload_plugin package to pub.dev <<'
#        uses: k-paxian/dart-package-publisher@master
#        with:
#          accessToken: ${{ secrets.PUB_ACCESS_TOKEN }}
#          refreshToken: ${{ secrets.PUB_REFRESH_TOKEN }}
#          skipTests: true
#          format: true
#          relativePath: packages/flutter_web_cos_upload_plugin